name: wekala
description: wekala

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+9

environment:
  sdk: ">=2.2.2 <3.0.0"
module:
  androidX: true
dependencies:
  cached_network_image: ^3.1.0
  carousel_slider: ^4.0.0-nullsafety.0
  cloud_firestore: ^2.4.0
  cupertino_icons: ^1.0.3
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  firebase_messaging: ^10.0.4
  flutter:
    sdk: flutter
  flutter_html: ^2.1.1
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.4.0-nullsafety.3
  flutter_svg: ^0.22.0
  fluttertoast: ^8.0.8-nullsafety.0
  global_configuration: 2.0.0-nullsafety.0
  google_maps_flutter: ^2.0.6
  google_sign_in: ^5.0.7
  html: ^0.15.0
  intl_utils: ^2.4.0
  location: ^4.3.0
  location_platform_interface: ^2.3.0
  mvc_pattern: ^7.4.0
  plugin_platform_interface: ^2.0.1
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  url_launcher: ^6.0.9
  webview_flutter: ^2.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: 0.17.0
  http: 0.13.3
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/cfg/
    - assets/img/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/ProductSans-Thin.ttf
          weight: 200
        - asset: assets/fonts/ProductSans-Light.ttf
          weight: 300
        - asset: assets/fonts/ProductSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/ProductSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/ProductSans-Bold.ttf
          weight: 600
        - asset: assets/fonts/ProductSans-Black.ttf
          weight: 700
        - asset: assets/fonts/ProductSans-Black.ttf
          weight: 800
        - asset: assets/fonts/ProductSans-Black.ttf
          weight: 900
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: assets/fonts/TrajanPro.ttf
  #       - asset: assets/fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-assets/fonts/#from-packages
flutter_intl:
  enabled: true
